
title: QA Site for Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

repo_name: "This-should-be-overridden-by-github-actions-script"

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "This-should-be-overridden-by-github-actions-script"
repo: ucsb-cs156-s23/team02-s23-5pm-1
owner: ucsb-cs156-s23
repo_name: team02-s23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NDE3MDg3","is_bot":false,"login":"cmfisher606","name":""},"headRefName":"Chris-BookTable","number":35,"title":"cf - Book Class added to Table","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-1/pull/35"}]
