
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-5pm-1
owner: ucsb-cs156-s23
repo_name: team02-s23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5Mjc3NDgy","is_bot":false,"login":"JamesEllenstein","name":"James Ellenstein"},"headRefName":"james-issue12Courses","number":45,"title":"je- finished issue 12 for Courses","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-1/pull/45"}]
